### ISSUE TITLE
Support for vst4free.com?

### ISSUE THREAD

**Issue by Boscop** [sdunnemucklow/VSTManager#1]
Is it possible to make it work with vst4free.com?
Or will every new version have a different zip URL?

**Comment by getdunne** [comment]
Hi Boscop. Good question -- thank you. The main problem is that VSTManager expects every .zip archive to contain exactly one folder, whose name is as given in the "folder" column of the store.csv file, but most people don't structure their .zip files this way.

In retrospect, this is an unnecessary restriction, and creates more problems than it solves. I've just added a new "Unzip-to-specified-folder" branch, which simply creates the necessary folder (by appending the folder name from store.zip to the user's local-folder path) and unzips into that. Try the updated version (direct link https://github.com/sdunnemucklow/VSTManager/blob/Unzip-to-specified-folder/prebuilt/VSTManager.exe) and enter http://getdunne.net/vst4free as the store URL.

Point a web browser to the same URL http://getdunne.net/vst4free/ to see how I set this up. That URL points to a folder that contains only a store.csv file, plus an index.php which provides a human-friendly listing with some explanatory notes. To create your own VST store, you need only create a similar store.csv file and put it somewhere where it can be accessed via HTTP, adding as many line-items as you wish for individual VST downloads (on vst4free or anywhere else).

I'm not ready to fold the new "Unzip-to-specified-folder" branch into the master, until I get time to beat it up a bit and make sure the change hasn't broken anything except expectations about .zip structure. Any feedback will be greatly appreciated.

**Comment by twobob** [comment]
Seems to work fine on Win 10 64. 
Is there no "Bitness" support in the meta? Seems like separating 64 bit installs is even more critically important given the deprecated status of the 32 bit offerings... Any clues?

Hmm further eyeballing of that file makes me realise that this thing points anywhere. And currently No, there is no meta for 64 bitness. Correct?

at a pinch maybe some sort of wangle for the PE header? 
$ file R:/StingerMax/StingerMax/StingerMax.dll
R:/StingerMax/StingerMax/StingerMax.dll: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows

The magic and offsets and expected values are documented best here and look pretty easy to port
https://stackoverflow.com/a/495305/293792

Given this one could make a far better judgement of sane install locations.

**Comment by getdunne** [comment]
Thank you for the link. I'll follow up on this when I get some time, but probably not for a while as I'm busy on other projects at the moment.

**Comment by Isch82Fucker** [comment]
Nice

**Comment by Boscop** [comment]
@getdunne Any update on this? :)

**Comment by getdunne** [comment]
Hi @Boscop. I've been working on a new product (https://www.pluginguru.com/products/unify-standard/) for the last year and a half. It may be some time before I get back to VST Manager.

**Comment by getdunne** [comment]
This was a student project. No longer actively maintained.
