### ISSUE TITLE
SmartScreen is giving a false positive.

### ISSUE THREAD

**Issue by Stargate38** [sdunnemucklow/VSTManager#4]
When I try to run VSTManager 1.3 (from /tree/master/prebuilt), I get this message from Microsoft's SmartScreen (I've already checked on VirusTotal, and your program is clean). I can't post a screenshot of it (I get "Something went really wrong, and we can't process that file. Try Again"), so I'll just put it in text:

`Malicious file

This application may cause damage to your device. Sensitive personal data
may also be at risk.

App:        VSTManager.exe
Publisher: Unknown publisher
Ignore Windows malware warning and run anyway.

Don't run`

I know I could easily click "Run anyway", but what's triggering it?

**Comment by getdunne** [comment]
I ran into this problem myself the other day. It's a false-positive glitch in the latest Windows Defender (SmartScreen). I have already reported this to Microsoft, and have received confirmation from them that it is indeed a false positive. The problem will probably go away at some point when Defender updates its detection database, but for now, it's OK to "run anyway". If you have any concerns, you can build the executable yourself from the source code.
